/**
 * invoicing-api — /credit-notes handlers (Wave 5 / Phase 8).
 *
 * Endpoints:
 *   GET    /credit-notes                  — list
 *   POST   /credit-notes                  — create draft
 *   GET    /credit-notes/:id              — detail
 *   POST   /credit-notes/:id/issue        — draft → issued
 *   POST   /credit-notes/:id/apply        — issued → applied; bumps applied_cents
 *                                            and stamps invoice_id if not set
 *   POST   /credit-notes/:id/void         — any non-voided → voided (stamps voided_at)
 *
 * Drifts from API-contract §6 (DB-wins reconcile; docs reconcile in 5.4):
 *   - DB has no `void_reason` column on credit_notes (verified 2026-05-15).
 *     The handler accepts a free-text reason for the wire/audit surface but
 *     does not persist it on the row; the audit-log row generated by future
 *     triggers (when wired) will carry the caller's reason via request context.
 *   - Wave 6 / Phase 9 closes R-W5-CN-01: the apply handler now INSERTs
 *     a row into credit_note_allocations; triggers maintain
 *     credit_notes.applied_cents + status and the invoice rollup
 *     (balance_cents + payment_status). The schema-master §9.6
 *     synthetic-payments-row strategy was rejected (payments.amount_cents > 0
 *     CHECK + payment_method_id FK); allocations is the canonical ledger.
 *   - The DB CHECK `applied_cents <= amount_cents` is the hard floor; the
 *     handler pre-validates server-side to surface a clean 422 before
 *     hitting the trigger.
 */

import type { Ctx } from '../../_shared/route.ts';
import { ok, err, ApiError, fromApiError } from '../../_shared/responses.ts';
import { requireCaller } from '../../_shared/tenant.ts';
import {
  CreditNoteApplySchema,
  CreditNoteCreateSchema,
  CreditNoteIssueSchema,
  CreditNoteSchema,
  CreditNoteVoidSchema,
  type CreditNote,
} from '../../_shared/types.ts';
import { assertTransition, WorkflowError } from '../../_shared/workflow.ts';
import {
  admin,
  decodeCursor,
  paginate,
  parseBody,
  parseLimit,
  requireCap,
  respondWithIdempotency,
  type Caller,
} from '../../_shared/handler-helpers.ts';
import { getNextDocNumber, NumberingError } from '../../_shared/numbering.ts';

const CREDIT_NOTE_COLS =
  'id, org_id, credit_note_number, customer_id, invoice_id, issue_date, status, reason, ' +
  'currency_code, amount_cents, applied_cents, notes, voided_at, created_at, updated_at';

interface CreditNoteRow {
  id: string;
  org_id: string;
  credit_note_number: string;
  customer_id: string;
  invoice_id: string | null;
  issue_date: string;
  status: string;
  reason: string | null;
  currency_code: string;
  amount_cents: number;
  applied_cents: number;
  notes: string | null;
  voided_at: string | null;
  created_at: string;
  updated_at: string;
}

function rowToCreditNote(row: CreditNoteRow): CreditNote {
  return CreditNoteSchema.parse(row);
}

function workflowToApiError(e: unknown): never {
  if (e instanceof WorkflowError) {
    throw new ApiError('STATE_CONFLICT', e.message, 409, {
      machine: e.machine,
      from: e.from,
      to: e.to,
    });
  }
  throw e;
}

async function fetchCreditNoteRow(caller: Caller, id: string): Promise<CreditNoteRow> {
  const { data, error } = await admin()
    .from('credit_notes')
    .select(CREDIT_NOTE_COLS)
    .eq('id', id)
    .eq('org_id', caller.orgId)
    .is('deleted_at', null)
    .maybeSingle();
  if (error) {
    throw new ApiError('INTERNAL_ERROR', 'credit note lookup failed', 500, {
      detail: error.message,
    });
  }
  if (!data) throw new ApiError('NOT_FOUND', 'credit note not found', 404);
  return data as CreditNoteRow;
}

async function nextCreditNoteNumber(orgId: string): Promise<string> {
  try {
    return await getNextDocNumber(admin(), orgId, 'credit_note');
  } catch (e) {
    if (e instanceof NumberingError) {
      throw new ApiError('INTERNAL_ERROR', 'next_doc_number credit_note failed', 500, {
        detail: e.message,
      });
    }
    throw e;
  }
}

// =========================================================================
// GET /credit-notes
// =========================================================================
export async function listCreditNotes({ req, url }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.read');
    const limit = parseLimit(url);
    const cursor = decodeCursor(url.searchParams.get('cursor'));
    const status = url.searchParams.get('status');
    const customerId = url.searchParams.get('customer_id');
    const invoiceId = url.searchParams.get('invoice_id');
    const currency = url.searchParams.get('currency_code');

    let query = admin()
      .from('credit_notes')
      .select(CREDIT_NOTE_COLS)
      .eq('org_id', caller.orgId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false })
      .order('id', { ascending: false })
      .limit(limit + 1);

    if (status) query = query.eq('status', status);
    if (customerId) query = query.eq('customer_id', customerId);
    if (invoiceId) query = query.eq('invoice_id', invoiceId);
    if (currency) query = query.eq('currency_code', currency);
    if (cursor) {
      query = query.or(
        `created_at.lt.${cursor.created_at},and(created_at.eq.${cursor.created_at},id.lt.${cursor.id})`,
      );
    }

    const { data, error } = await query;
    if (error) {
      return err(
        'INTERNAL_ERROR',
        'credit note list query failed',
        { detail: error.message },
        500,
        { req },
      );
    }
    const rows = (data ?? []) as CreditNoteRow[];
    const { items, next_cursor } = paginate(rows, limit);
    return ok({ items: items.map(rowToCreditNote), next_cursor }, undefined, { req });
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}

// =========================================================================
// GET /credit-notes/:id
// =========================================================================
export async function getCreditNote({ req, params }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.read');
    const row = await fetchCreditNoteRow(caller, params.id);
    return ok(rowToCreditNote(row), undefined, { req });
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}

// =========================================================================
// POST /credit-notes
// =========================================================================
export async function createCreditNote({ req }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.write');
    const body = await parseBody(req, CreditNoteCreateSchema);

    return await respondWithIdempotency(
      req,
      caller,
      'invoicing-api',
      'POST /credit-notes',
      body,
      async () => {
        // Verify customer in caller's org.
        const { data: customer, error: cErr } = await admin()
          .from('customers')
          .select('id')
          .eq('id', body.customer_id)
          .eq('org_id', caller.orgId)
          .maybeSingle();
        if (cErr) {
          throw new ApiError('INTERNAL_ERROR', 'customer lookup failed', 500, {
            detail: cErr.message,
          });
        }
        if (!customer) {
          throw new ApiError('VALIDATION_ERROR', 'customer_id not found in caller org', 422);
        }

        // If invoice_id passed, verify it belongs to caller's org and currency
        // matches (credit-notes can only apply against same-currency invoices).
        if (body.invoice_id) {
          const { data: invoice, error: iErr } = await admin()
            .from('invoices')
            .select('id, currency_code, customer_id')
            .eq('id', body.invoice_id)
            .eq('org_id', caller.orgId)
            .is('deleted_at', null)
            .maybeSingle();
          if (iErr) {
            throw new ApiError('INTERNAL_ERROR', 'invoice lookup failed', 500, {
              detail: iErr.message,
            });
          }
          if (!invoice) {
            throw new ApiError('VALIDATION_ERROR', 'invoice_id not found in caller org', 422);
          }
          const inv = invoice as { currency_code: string; customer_id: string };
          if (inv.currency_code !== body.currency_code) {
            throw new ApiError(
              'VALIDATION_ERROR',
              `credit note currency_code ${body.currency_code} does not match invoice ${inv.currency_code}`,
              422,
            );
          }
          if (inv.customer_id !== body.customer_id) {
            throw new ApiError(
              'VALIDATION_ERROR',
              'invoice customer does not match credit_note customer',
              422,
            );
          }
        }

        const cnNumber = await nextCreditNoteNumber(caller.orgId);
        const issue = body.issue_date ?? new Date().toISOString().slice(0, 10);

        const { data, error } = await admin()
          .from('credit_notes')
          .insert({
            org_id: caller.orgId,
            credit_note_number: cnNumber,
            customer_id: body.customer_id,
            invoice_id: body.invoice_id ?? null,
            issue_date: issue,
            status: 'draft',
            reason: body.reason ?? null,
            currency_code: body.currency_code,
            amount_cents: body.amount_cents,
            applied_cents: 0,
            notes: body.notes ?? null,
            created_by: caller.userId,
          })
          .select(CREDIT_NOTE_COLS)
          .single();
        if (error || !data) {
          throw new ApiError('INTERNAL_ERROR', 'credit note insert failed', 500, {
            detail: error?.message,
          });
        }
        return { status: 201, body: { data: rowToCreditNote(data as CreditNoteRow) } };
      },
    );
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}

// =========================================================================
// POST /credit-notes/:id/issue
// =========================================================================
export async function issueCreditNote({ req, params }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.issue');
    const body = await parseBody(req, CreditNoteIssueSchema);
    const id = params.id;

    return await respondWithIdempotency(
      req,
      caller,
      'invoicing-api',
      'POST /credit-notes/:id/issue',
      body,
      async () => {
        const existing = await fetchCreditNoteRow(caller, id);
        try {
          assertTransition('credit_note', existing.status, 'issued');
        } catch (e) {
          workflowToApiError(e);
        }
        const nowIso = new Date().toISOString();
        const { data, error } = await admin()
          .from('credit_notes')
          .update({ status: 'issued', updated_at: nowIso })
          .eq('id', id)
          .eq('org_id', caller.orgId)
          .select(CREDIT_NOTE_COLS)
          .single();
        if (error || !data) {
          throw new ApiError('INTERNAL_ERROR', 'credit note issue failed', 500, {
            detail: error?.message,
          });
        }
        return { status: 200, body: { data: rowToCreditNote(data as CreditNoteRow) } };
      },
    );
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}

// =========================================================================
// POST /credit-notes/:id/apply
// =========================================================================
/**
 * Wave 6 / Phase 9 / closes R-W5-CN-01.
 *
 * Apply now INSERTs a row into credit_note_allocations. Triggers handle
 * the rest:
 *   - tg_cna_sync_cn syncs credit_notes.applied_cents to SUM(amount_cents)
 *     and flips status='applied' when fully consumed.
 *   - tg_cna_recompute_invoice fires recompute_invoice_totals on the
 *     parent invoice, which now subtracts CN allocations from
 *     balance_cents and updates payment_status accordingly.
 *
 * UNIQUE (credit_note_id, invoice_id, deleted_at) on the allocations table
 * means a second apply of the same CN to the same invoice 23505-conflicts
 * — surface as STATE_CONFLICT 409 so the caller knows to PATCH the
 * existing allocation row (or delete + re-insert with new amount).
 */
export async function applyCreditNote({ req, params }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.apply');
    const body = await parseBody(req, CreditNoteApplySchema);
    const id = params.id;

    return await respondWithIdempotency(
      req,
      caller,
      'invoicing-api',
      'POST /credit-notes/:id/apply',
      body,
      async () => {
        const existing = await fetchCreditNoteRow(caller, id);
        try {
          assertTransition('credit_note', existing.status, 'applied');
        } catch (e) {
          workflowToApiError(e);
        }

        // Verify target invoice is in caller's org + currency matches the CN.
        const { data: invoice, error: iErr } = await admin()
          .from('invoices')
          .select('id, currency_code, customer_id, status')
          .eq('id', body.invoice_id)
          .eq('org_id', caller.orgId)
          .is('deleted_at', null)
          .maybeSingle();
        if (iErr) {
          throw new ApiError('INTERNAL_ERROR', 'invoice lookup failed', 500, {
            detail: iErr.message,
          });
        }
        if (!invoice) {
          throw new ApiError('VALIDATION_ERROR', 'invoice_id not found in caller org', 422);
        }
        const inv = invoice as { currency_code: string; customer_id: string; status: string };
        if (inv.currency_code !== existing.currency_code) {
          throw new ApiError(
            'VALIDATION_ERROR',
            `credit note currency ${existing.currency_code} does not match invoice ${inv.currency_code}`,
            422,
          );
        }
        if (inv.customer_id !== existing.customer_id) {
          throw new ApiError(
            'VALIDATION_ERROR',
            'invoice customer does not match credit_note customer',
            422,
          );
        }

        // Pre-flight: the trigger's CHECK (applied_sum <= amount) would
        // surface as a 500 if we hit it; surface a clean 422 here.
        const newApplied = existing.applied_cents + body.amount_cents;
        if (newApplied > existing.amount_cents) {
          throw new ApiError(
            'VALIDATION_ERROR',
            `applied_cents ${newApplied} would exceed credit_note.amount_cents ${existing.amount_cents}`,
            422,
          );
        }

        const { error: allocErr } = await admin()
          .from('credit_note_allocations')
          .insert({
            org_id: caller.orgId,
            credit_note_id: id,
            invoice_id: body.invoice_id,
            amount_cents: body.amount_cents,
            created_by: caller.userId,
            updated_by: caller.userId,
          });
        if (allocErr) {
          if (allocErr.code === '23505') {
            throw new ApiError(
              'STATE_CONFLICT',
              'credit_note already has an allocation against this invoice',
              409,
            );
          }
          throw new ApiError('INTERNAL_ERROR', 'credit_note_allocations insert failed', 500, {
            detail: allocErr.message,
          });
        }

        // Re-fetch the CN row to surface the trigger-updated applied_cents
        // + status. tg_cna_sync_cn fires synchronously inside the same
        // transaction, so the read picks up the new state.
        const updated = await fetchCreditNoteRow(caller, id);
        return { status: 200, body: { data: rowToCreditNote(updated) } };
      },
    );
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}

// =========================================================================
// POST /credit-notes/:id/void
// =========================================================================
export async function voidCreditNote({ req, params }: Ctx): Promise<Response> {
  try {
    const caller = requireCaller(req);
    requireCap(caller, 'credit_notes.write');
    const body = await parseBody(req, CreditNoteVoidSchema);
    const id = params.id;

    return await respondWithIdempotency(
      req,
      caller,
      'invoicing-api',
      'POST /credit-notes/:id/void',
      body,
      async () => {
        const existing = await fetchCreditNoteRow(caller, id);
        try {
          assertTransition('credit_note', existing.status, 'voided');
        } catch (e) {
          workflowToApiError(e);
        }
        const nowIso = new Date().toISOString();
        // Note: schema has no void_reason column; body.reason is accepted for
        // wire-surface accountability but not persisted on the row. Phase 9
        // wires audit-log enrichment.
        const _unused = body.reason; // explicit acknowledgement
        const { data, error } = await admin()
          .from('credit_notes')
          .update({
            status: 'voided',
            voided_at: nowIso,
            updated_at: nowIso,
          })
          .eq('id', id)
          .eq('org_id', caller.orgId)
          .select(CREDIT_NOTE_COLS)
          .single();
        if (error || !data) {
          throw new ApiError('INTERNAL_ERROR', 'credit note void failed', 500, {
            detail: error?.message,
          });
        }
        return { status: 200, body: { data: rowToCreditNote(data as CreditNoteRow) } };
      },
    );
  } catch (e) {
    if (e instanceof ApiError) return fromApiError(e, req);
    throw e;
  }
}
