/**
 * JournalEntryListPage — Wave 8 / Phase 12. Filters on status / source_type /
 * source_id / from / to. Click row -> detail.
 */
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';

import { ExportButton } from '@/components/exports/ExportButton';
import { JEStatusBadge } from '@/components/finance/JEStatusBadge';
import { EmptyState } from '@/components/ui/EmptyState';
import { ErrorState } from '@/components/ui/ErrorState';
import { FilterChip } from '@/components/ui/FilterChip';
import { TableSkeleton } from '@/components/ui/Skeleton';
import { formatDate } from '@/lib/format';
import { useCapabilities } from '@/lib/hooks/useCapabilities';
import { journalEntryKeys } from '@/lib/queryKeys/journalEntries';
import {
  listJournalEntries,
  type JournalEntryListFilters,
} from '@/lib/services/journalEntriesService';
import {
  JournalEntrySourceTypeSchema,
  JournalEntryStateSchema,
  type JournalEntrySourceType,
} from '@/lib/types';
import type { JournalEntryState } from '@/lib/workflow';

const STATUS_VALUES = JournalEntryStateSchema.options;
const SOURCE_VALUES = JournalEntrySourceTypeSchema.options;

export default function JournalEntryListPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const status = searchParams.get('status') ?? '';
  const sourceType = searchParams.get('source_type') ?? '';
  const sourceId = searchParams.get('source_id') ?? '';
  const from = searchParams.get('from') ?? '';
  const to = searchParams.get('to') ?? '';
  const cursor = searchParams.get('cursor') ?? undefined;

  const [sourceIdInput, setSourceIdInput] = useState(sourceId);
  const { can } = useCapabilities();
  const canWrite = can('finance.journal_entries.write');

  const filters: JournalEntryListFilters = {};
  if (status) filters.status = status;
  if (sourceType) filters.source_type = sourceType as JournalEntrySourceType;
  if (sourceId) filters.source_id = sourceId;
  if (from) filters.from = from;
  if (to) filters.to = to;
  if (cursor) filters.cursor = cursor;

  const query = useQuery({
    queryKey: journalEntryKeys.list(filters),
    queryFn: () => listJournalEntries(filters),
    staleTime: 15_000,
    placeholderData: keepPreviousData,
  });

  function update(next: Record<string, string | undefined>): void {
    const sp = new URLSearchParams(searchParams);
    for (const [k, v] of Object.entries(next)) {
      if (v === undefined || v === '') sp.delete(k);
      else sp.set(k, v);
    }
    if (Object.keys(next).some((k) => k !== 'cursor')) sp.delete('cursor');
    setSearchParams(sp, { replace: true });
  }

  function toggleStatus(value: JournalEntryState) {
    update({ status: status === value ? '' : value });
  }

  return (
    <div className="mx-auto max-w-6xl space-y-4 px-6 py-8">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div className="space-y-1">
          <h1 className="text-2xl font-semibold">Journal entries</h1>
          <p className="text-sm text-fg-muted">
            General-ledger entries — auto-generated by source events and manual entries.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <ExportButton entity="journal_entries" />
          <ExportButton entity="journal_entries" label="Export with lines" params={{ expand: 'lines' }} />
          {canWrite && (
            <Link
              to="/finance/journal-entries/new"
              className="rounded-md bg-brand px-3 py-1 text-sm font-medium text-brand-fg hover:opacity-90"
              data-testid="new-je-link"
            >
              New journal entry
            </Link>
          )}
        </div>
      </header>

      <form
        className="flex flex-wrap items-end gap-3"
        role="search"
        aria-label="Journal entry filters"
        onSubmit={(e) => {
          e.preventDefault();
          update({ source_id: sourceIdInput });
        }}
      >
        <select
          value={sourceType}
          onChange={(e) => update({ source_type: e.target.value })}
          className="rounded-md border border-border bg-bg px-2 py-1 text-sm text-fg focus:outline-none focus:ring-2 focus:ring-brand"
          aria-label="Source type"
          data-testid="source-type-select"
        >
          <option value="">All sources</option>
          {SOURCE_VALUES.map((s) => (
            <option key={s} value={s}>
              {s}
            </option>
          ))}
        </select>
        <input
          type="text"
          value={sourceIdInput}
          onChange={(e) => setSourceIdInput(e.target.value)}
          placeholder="Source ID"
          className="w-72 rounded-md border border-border bg-bg px-2 py-1 font-mono text-xs text-fg focus:outline-none focus:ring-2 focus:ring-brand"
          aria-label="Source ID"
        />
        <input
          type="date"
          value={from}
          onChange={(e) => update({ from: e.target.value })}
          className="rounded-md border border-border bg-bg px-2 py-1 text-sm text-fg focus:outline-none focus:ring-2 focus:ring-brand"
          aria-label="From"
        />
        <input
          type="date"
          value={to}
          onChange={(e) => update({ to: e.target.value })}
          className="rounded-md border border-border bg-bg px-2 py-1 text-sm text-fg focus:outline-none focus:ring-2 focus:ring-brand"
          aria-label="To"
        />
        <button
          type="submit"
          className="rounded-md bg-brand px-3 py-1 text-sm font-medium text-brand-fg hover:opacity-90"
        >
          Apply
        </button>
      </form>

      <div
        className="flex flex-wrap items-center gap-2"
        role="group"
        aria-label="Status filter"
        data-testid="status-chips"
      >
        {STATUS_VALUES.map((s) => (
          <FilterChip
            key={s}
            label={s}
            active={status === s}
            onClick={() => toggleStatus(s)}
            testId={`status-chip-${s}`}
          />
        ))}
      </div>

      {query.isLoading && <TableSkeleton rows={6} cols={6} />}
      {query.error && <ErrorState title="Could not load journal entries" error={query.error} />}
      {query.data && query.data.items.length === 0 && (
        <EmptyState title="No journal entries found" description="Try a different filter." />
      )}

      {query.data && query.data.items.length > 0 && (
        <div className="overflow-x-auto rounded-md border border-border">
          <table className="min-w-full divide-y divide-border text-sm">
            <thead className="bg-bg-muted text-left text-xs uppercase tracking-wide text-fg-subtle">
              <tr>
                <th scope="col" className="px-3 py-2 font-medium">Entry #</th>
                <th scope="col" className="px-3 py-2 font-medium">Status</th>
                <th scope="col" className="px-3 py-2 font-medium">Date</th>
                <th scope="col" className="px-3 py-2 font-medium">Source</th>
                <th scope="col" className="px-3 py-2 font-medium">Description</th>
                <th scope="col" className="px-3 py-2 font-medium">Currency</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {query.data.items.map((je) => (
                <tr key={je.id} className="hover:bg-bg-muted">
                  <td className="px-3 py-2 font-mono">
                    <Link
                      to={`/finance/journal-entries/${je.id}`}
                      className="text-brand hover:underline focus:outline-none focus:ring-2 focus:ring-brand"
                    >
                      {je.entry_number}
                    </Link>
                  </td>
                  <td className="px-3 py-2">
                    <JEStatusBadge status={je.status} />
                  </td>
                  <td className="px-3 py-2 text-fg-muted">{formatDate(je.entry_date)}</td>
                  <td className="px-3 py-2 text-fg-muted">
                    {je.source_type ?? '—'}
                  </td>
                  <td className="px-3 py-2 max-w-xs truncate text-fg-muted">
                    {je.description ?? '—'}
                  </td>
                  <td className="px-3 py-2 font-mono text-fg-muted">{je.currency_code}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {query.data?.next_cursor && (
        <div className="flex justify-end">
          <button
            type="button"
            onClick={() => update({ cursor: query.data?.next_cursor ?? undefined })}
            className="rounded-md border border-border bg-bg px-3 py-1 text-sm text-fg hover:bg-bg-muted"
          >
            Next page
          </button>
        </div>
      )}
    </div>
  );
}
