/**
 * pdf-worker — shared template primitives.
 *
 * Renders org-branded invoice / quote / payment-receipt PDFs via pdf-lib
 * (constitutional lock-in per TS1/07-architecture/00-SYSTEM-ARCHITECTURE.md §0
 * and the Wave-0 placeholder at `_shared/pdf.ts`).
 *
 * pdf-lib is Deno-friendly (pure JS, no native deps), no fontkit needed
 * because we restrict to the 14 built-in PDF fonts (Helvetica family).
 *
 * Template philosophy:
 *   - Single Letter-sized page is enough for P0 invoices/quotes/receipts.
 *     Overflow to multi-page is a Phase 19 polish / R-W10-S3-PDF-01.
 *   - Brand color: a hex string from org_branding.primary_color. We don't
 *     try to read CSS vars; the row is the source of truth.
 *   - Logo: skipped if logo_url is null or the fetch fails. Render the
 *     org name as a text header instead.
 *   - Footer: invoice_pdf_footer or quote_pdf_footer from org_branding,
 *     falling back to a generic "Generated by Team1" string.
 */

import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from 'https://esm.sh/pdf-lib@1.17.1';

export interface OrgBranding {
  org_name: string;
  logo_url: string | null;
  primary_color: string;   // hex
  accent_color: string;    // hex
  invoice_pdf_footer: string | null;
  quote_pdf_footer: string | null;
}

export interface LineItem {
  description: string;
  quantity: number;
  unit_price_cents: number;
  line_total_cents: number;
}

export interface InvoiceLikeData {
  number: string;
  date: string;          // ISO YYYY-MM-DD
  due_date?: string | null;
  currency_code: string;
  customer_name: string;
  customer_address?: string | null;
  notes?: string | null;
  lines: LineItem[];
  subtotal_cents: number;
  tax_cents: number;
  total_cents: number;
  /** invoice-only: amount paid so far + balance */
  paid_cents?: number;
  balance_cents?: number;
}

export interface PaymentReceiptData {
  number: string;
  date: string;
  currency_code: string;
  customer_name: string;
  customer_address?: string | null;
  payment_method?: string | null;
  reference?: string | null;
  amount_cents: number;
  /** optional invoice context. */
  invoice_number?: string | null;
  notes?: string | null;
}

// ---- color + currency helpers ---------------------------------------------

function hexToRgb01(hex: string): { r: number; g: number; b: number } {
  const m = /^#?([0-9a-fA-F]{6})$/.exec(hex.trim());
  if (!m) return { r: 0.06, g: 0.09, b: 0.16 }; // slate-900 fallback
  const v = parseInt(m[1], 16);
  return {
    r: ((v >> 16) & 0xff) / 255,
    g: ((v >> 8) & 0xff) / 255,
    b: (v & 0xff) / 255,
  };
}

export function formatMoney(cents: number, currency: string): string {
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }).format(cents / 100);
  } catch {
    return `${(cents / 100).toFixed(2)} ${currency}`;
  }
}

// ---- low-level draw helpers -----------------------------------------------

interface DrawCtx {
  page: PDFPage;
  font: PDFFont;
  bold: PDFFont;
}

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  color = rgb(0, 0, 0),
): void {
  page.drawText(text, { x, y, size, font, color });
}

// ---- header + footer ------------------------------------------------------

async function drawHeader(
  pdf: PDFDocument,
  ctx: DrawCtx,
  branding: OrgBranding,
  docTitle: string,
  docNumber: string,
): Promise<void> {
  const { page, font, bold } = ctx;
  const { width, height } = page.getSize();
  const brand = hexToRgb01(branding.primary_color);
  const brandColor = rgb(brand.r, brand.g, brand.b);

  // Top brand band (12pt high).
  page.drawRectangle({ x: 0, y: height - 12, width, height: 12, color: brandColor });

  // Org name / logo on the left.
  let logoDrawn = false;
  if (branding.logo_url) {
    try {
      const res = await fetch(branding.logo_url);
      if (res.ok) {
        const bytes = new Uint8Array(await res.arrayBuffer());
        const ct = res.headers.get('content-type') ?? '';
        let img;
        if (ct.includes('png') || branding.logo_url.endsWith('.png')) {
          img = await pdf.embedPng(bytes);
        } else if (ct.includes('jpeg') || ct.includes('jpg') || /\.jpe?g$/.test(branding.logo_url)) {
          img = await pdf.embedJpg(bytes);
        }
        if (img) {
          const maxH = 40;
          const scale = maxH / img.height;
          const w = img.width * scale;
          page.drawImage(img, { x: 40, y: height - 60, width: w, height: maxH });
          logoDrawn = true;
        }
      }
    } catch {
      // Fallback to text header.
    }
  }
  if (!logoDrawn) {
    drawText(page, branding.org_name, 40, height - 50, bold, 16, brandColor);
  }

  // Doc title + number on the right.
  drawText(page, docTitle.toUpperCase(), width - 200, height - 40, bold, 18, brandColor);
  drawText(page, docNumber, width - 200, height - 60, font, 12);
}

function drawFooter(ctx: DrawCtx, footerText: string | null): void {
  const { page, font } = ctx;
  const { width } = page.getSize();
  const text = footerText ?? 'Generated by Team1.';
  drawText(page, text, 40, 30, font, 8, rgb(0.42, 0.46, 0.52));
  drawText(page, `Page 1`, width - 60, 30, font, 8, rgb(0.42, 0.46, 0.52));
}

// ---- invoice/quote-like layout --------------------------------------------

async function renderInvoiceLike(
  data: InvoiceLikeData,
  branding: OrgBranding,
  docTitle: string,
  footerText: string | null,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`${docTitle} ${data.number}`);
  pdf.setProducer('Team1 pdf-worker');
  pdf.setCreator('Team1');

  const page = pdf.addPage([612, 792]); // US Letter
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ctx: DrawCtx = { page, font, bold };

  await drawHeader(pdf, ctx, branding, docTitle, data.number);

  let y = 700;

  // Meta block (date, due, currency).
  drawText(page, `Date: ${data.date}`, 40, y, font, 10);
  if (data.due_date) {
    drawText(page, `Due: ${data.due_date}`, 200, y, font, 10);
  }
  drawText(page, `Currency: ${data.currency_code}`, 360, y, font, 10);
  y -= 30;

  // Bill to.
  drawText(page, 'Bill To:', 40, y, bold, 10);
  drawText(page, data.customer_name, 100, y, font, 10);
  y -= 14;
  if (data.customer_address) {
    for (const line of data.customer_address.split('\n').slice(0, 4)) {
      drawText(page, line, 100, y, font, 9);
      y -= 12;
    }
  }
  y -= 18;

  // Lines header.
  const brand = hexToRgb01(branding.primary_color);
  page.drawRectangle({ x: 40, y: y - 4, width: 532, height: 20, color: rgb(brand.r, brand.g, brand.b) });
  drawText(page, 'Description', 50, y + 4, bold, 9, rgb(1, 1, 1));
  drawText(page, 'Qty',          340, y + 4, bold, 9, rgb(1, 1, 1));
  drawText(page, 'Unit Price',   400, y + 4, bold, 9, rgb(1, 1, 1));
  drawText(page, 'Line Total',   490, y + 4, bold, 9, rgb(1, 1, 1));
  y -= 20;

  // Lines body.
  for (const line of data.lines.slice(0, 25)) {
    const desc = line.description.length > 60 ? line.description.slice(0, 57) + '...' : line.description;
    drawText(page, desc, 50, y - 12, font, 9);
    drawText(page, String(line.quantity), 340, y - 12, font, 9);
    drawText(page, formatMoney(line.unit_price_cents, data.currency_code), 400, y - 12, font, 9);
    drawText(page, formatMoney(line.line_total_cents, data.currency_code), 490, y - 12, font, 9);
    y -= 18;
    if (y < 180) break; // single-page cap; multi-page deferred
  }

  // Totals block.
  y -= 10;
  page.drawLine({ start: { x: 360, y }, end: { x: 572, y }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
  y -= 16;
  drawText(page, 'Subtotal:', 360, y, font, 10);
  drawText(page, formatMoney(data.subtotal_cents, data.currency_code), 490, y, font, 10);
  y -= 14;
  drawText(page, 'Tax:', 360, y, font, 10);
  drawText(page, formatMoney(data.tax_cents, data.currency_code), 490, y, font, 10);
  y -= 14;
  drawText(page, 'Total:', 360, y, bold, 11);
  drawText(page, formatMoney(data.total_cents, data.currency_code), 490, y, bold, 11);

  if (typeof data.paid_cents === 'number' && typeof data.balance_cents === 'number') {
    y -= 14;
    drawText(page, 'Paid:', 360, y, font, 10);
    drawText(page, formatMoney(data.paid_cents, data.currency_code), 490, y, font, 10);
    y -= 14;
    drawText(page, 'Balance Due:', 360, y, bold, 11);
    drawText(page, formatMoney(data.balance_cents, data.currency_code), 490, y, bold, 11);
  }

  // Notes.
  if (data.notes) {
    y -= 30;
    drawText(page, 'Notes:', 40, y, bold, 9);
    y -= 12;
    for (const line of data.notes.split('\n').slice(0, 6)) {
      drawText(page, line.length > 110 ? line.slice(0, 107) + '...' : line, 40, y, font, 9);
      y -= 12;
    }
  }

  drawFooter(ctx, footerText);

  return await pdf.save();
}

export async function renderInvoicePdf(
  data: InvoiceLikeData,
  branding: OrgBranding,
): Promise<Uint8Array> {
  return await renderInvoiceLike(data, branding, 'Invoice', branding.invoice_pdf_footer);
}

export async function renderQuotePdf(
  data: InvoiceLikeData,
  branding: OrgBranding,
): Promise<Uint8Array> {
  return await renderInvoiceLike(data, branding, 'Quote', branding.quote_pdf_footer);
}

// ---- payment receipt -------------------------------------------------------

export async function renderPaymentReceiptPdf(
  data: PaymentReceiptData,
  branding: OrgBranding,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(`Payment Receipt ${data.number}`);
  pdf.setProducer('Team1 pdf-worker');
  pdf.setCreator('Team1');

  const page = pdf.addPage([612, 792]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ctx: DrawCtx = { page, font, bold };

  await drawHeader(pdf, ctx, branding, 'Payment Receipt', data.number);

  let y = 700;
  drawText(page, `Date: ${data.date}`, 40, y, font, 10);
  drawText(page, `Currency: ${data.currency_code}`, 360, y, font, 10);
  y -= 30;

  drawText(page, 'Received From:', 40, y, bold, 10);
  drawText(page, data.customer_name, 140, y, font, 10);
  y -= 14;
  if (data.customer_address) {
    for (const line of data.customer_address.split('\n').slice(0, 4)) {
      drawText(page, line, 140, y, font, 9);
      y -= 12;
    }
  }
  y -= 18;

  if (data.payment_method) {
    drawText(page, 'Method:', 40, y, bold, 10);
    drawText(page, data.payment_method, 140, y, font, 10);
    y -= 16;
  }
  if (data.reference) {
    drawText(page, 'Reference:', 40, y, bold, 10);
    drawText(page, data.reference, 140, y, font, 10);
    y -= 16;
  }
  if (data.invoice_number) {
    drawText(page, 'For Invoice:', 40, y, bold, 10);
    drawText(page, data.invoice_number, 140, y, font, 10);
    y -= 16;
  }
  y -= 14;

  // Amount block.
  const brand = hexToRgb01(branding.primary_color);
  page.drawRectangle({ x: 40, y: y - 30, width: 532, height: 50, color: rgb(brand.r, brand.g, brand.b) });
  drawText(page, 'Amount Received', 60, y - 6, bold, 12, rgb(1, 1, 1));
  drawText(page, formatMoney(data.amount_cents, data.currency_code), 400, y - 10, bold, 18, rgb(1, 1, 1));

  y -= 60;
  if (data.notes) {
    drawText(page, 'Notes:', 40, y, bold, 9);
    y -= 12;
    for (const line of data.notes.split('\n').slice(0, 6)) {
      drawText(page, line.length > 110 ? line.slice(0, 107) + '...' : line, 40, y, font, 9);
      y -= 12;
    }
  }

  drawFooter(ctx, branding.invoice_pdf_footer);

  return await pdf.save();
}
